name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  linux-tests:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
          set -o pipefail && swift test
    
  macos-tests:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          set -o pipefail && swift test